apiVersion: v1
kind: Service
metadata:
  name: hello-world-cluster-ip-service
spec:
  selector:
    app: hello-world-server
  type: ClusterIP
  ports:
  - name: hello-world-cluster-ip-service
    # port of the service that we'll access
    port: 80
    # port of the container that our service will redirect to
    targetPort: 8000
    protocol: TCP
