# this will be different from other configs because the api of the replicaSet is a different folder
apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: hello-world-server
  labels:
    app: hello-world-server

spec:
  selector:
    matchLabels:
      app: hello-world-server
  replicas: 2
  # Configuration of the pod (yml created for our pods)
  template: 
    metadata:
      name: hello-world-server
      labels:
        app: hello-world-server

    spec:
      containers:
        - name: hello-world-server
          image: hello-world
